#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : trace-cmd
Version  : 2.7
Release  : 1
URL      : https://git.kernel.org/pub/scm/linux/kernel/git/rostedt/trace-cmd.git/snapshot/trace-cmd-v2.7.tar.gz
Source0  : https://git.kernel.org/pub/scm/linux/kernel/git/rostedt/trace-cmd.git/snapshot/trace-cmd-v2.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: trace-cmd-bin = %{version}-%{release}
Requires: trace-cmd-lib = %{version}-%{release}
Requires: trace-cmd-license = %{version}-%{release}

%description
These files make up the code that create the trace-cmd programs.
This includes the GUI interface application kernelshark as well
as trace-graph and trace-view.

%package bin
Summary: bin components for the trace-cmd package.
Group: Binaries
Requires: trace-cmd-license = %{version}-%{release}

%description bin
bin components for the trace-cmd package.


%package lib
Summary: lib components for the trace-cmd package.
Group: Libraries
Requires: trace-cmd-license = %{version}-%{release}

%description lib
lib components for the trace-cmd package.


%package license
Summary: license components for the trace-cmd package.
Group: Default

%description license
license components for the trace-cmd package.


%prep
%setup -q -n trace-cmd-v2.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549995753
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1549995753
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/trace-cmd
cp COPYING %{buildroot}/usr/share/package-licenses/trace-cmd/COPYING
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/trace-cmd/COPYING.LIB
%make_install prefix=/usr libdir=/usr/lib64

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/trace-cmd

%files lib
%defattr(-,root,root,-)
/usr/lib64/trace-cmd/plugins/plugin_blk.so
/usr/lib64/trace-cmd/plugins/plugin_cfg80211.so
/usr/lib64/trace-cmd/plugins/plugin_function.so
/usr/lib64/trace-cmd/plugins/plugin_hrtimer.so
/usr/lib64/trace-cmd/plugins/plugin_jbd2.so
/usr/lib64/trace-cmd/plugins/plugin_kmem.so
/usr/lib64/trace-cmd/plugins/plugin_kvm.so
/usr/lib64/trace-cmd/plugins/plugin_mac80211.so
/usr/lib64/trace-cmd/plugins/plugin_sched_switch.so
/usr/lib64/trace-cmd/plugins/plugin_scsi.so
/usr/lib64/trace-cmd/plugins/plugin_tlb.so
/usr/lib64/trace-cmd/plugins/plugin_xen.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/trace-cmd/COPYING
/usr/share/package-licenses/trace-cmd/COPYING.LIB
